apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: whoami-helmrelease-indirect-1
spec:
  interval: 1m
  url: https://github.com/jwausle/gitops.git
  ref:
    branch: ${app_branch:=forgetToConfigure}
  timeout: 20s
  ignore: |
    # exclude all
    /*
    # include deploy dir
    !/helmcharts
